# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "amd-edf-demos"
BBFILE_PATTERN_amd-edf-demos = "^${LAYERDIR}/"
BBFILE_PRIORITY_amd-edf-demos = "5"

LAYERDEPENDS_amd-edf-demos = "core"
LAYERRECOMMENDS_amd-edf-demos = "\
    openembedded-layer \
    meta-amd-edf \
    amd-adaptive-socs-bsp \
    "

LAYERSERIES_COMPAT_amd-edf-demos = "scarthgap"
